"""Validate a real SET50 futures market-data file before it may enter replay.

Usage::

    uv run python scripts/validate_tfex_market_data.py \\
        --file backend/data/tfex/historical/raw/S50Z26/S50Z26_1m.csv \\
        --symbol S50Z26 \\
        --interval 1m \\
        --timezone Asia/Bangkok

Exit codes:

===  ===============================
0    PASS
1    PASS_WITH_WARNINGS
2    REJECTED
3    CONFIGURATION_OR_PROVENANCE_ERROR
===  ===============================

A human-readable report goes to stdout; ``--json`` also writes the machine-readable form.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

BACKEND_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(BACKEND_ROOT))

from app.tfex.calendar import HolidayStore, TradingCalendar
from app.tfex.config import load_config
from app.tfex.errors import ConfigurationError
from app.tfex.marketdata.csv_loader import load_bars
from app.tfex.marketdata.manifest import (
    build_manifest,
    file_sha256,
    load_manifest,
    manifest_path_for,
    save_manifest,
    write_report_json,
)
from app.tfex.marketdata.models import BarInterval, ValidationOutcome
from app.tfex.marketdata.validation import MarketDataValidator, ValidationSettings


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--file", required=True, help="market-data CSV to validate")
    parser.add_argument("--symbol", required=True, help="contract symbol, e.g. S50Z26")
    parser.add_argument("--interval", default="1m", choices=[i.value for i in BarInterval])
    parser.add_argument(
        "--timezone",
        default="Asia/Bangkok",
        help="timezone of naive timestamps in the file. Declared, never assumed.",
    )
    parser.add_argument("--json", help="also write the machine-readable report here")
    parser.add_argument(
        "--write-manifest",
        action="store_true",
        help="create a manifest beside the file if none exists (records it as UNVERIFIED)",
    )
    parser.add_argument(
        "--allow-derived-contract-calendar",
        action="store_true",
        help=(
            "permit a last trading day from the derived rule instead of the exchange-published "
            "calendar; the default refuses, per PART R of the data-readiness gate"
        ),
    )
    args = parser.parse_args(argv)

    data_file = Path(args.file)
    interval = BarInterval(args.interval)

    if not data_file.is_file():
        print(f"CONFIGURATION ERROR: no such file {data_file}", file=sys.stderr)
        return ValidationOutcome.CONFIGURATION_OR_PROVENANCE_ERROR.exit_code

    config = load_config()
    calendar = TradingCalendar(config, HolidayStore())
    validator = MarketDataValidator(
        config,
        calendar,
        settings=ValidationSettings(
            require_published_contract_calendar=not args.allow_derived_contract_calendar
        ),
    )

    try:
        loaded = load_bars(data_file, source_timezone=args.timezone, symbol=args.symbol)
    except ConfigurationError as exc:
        print(f"CONFIGURATION ERROR: {exc}", file=sys.stderr)
        return ValidationOutcome.CONFIGURATION_OR_PROVENANCE_ERROR.exit_code

    try:
        manifest = load_manifest(data_file)
    except ConfigurationError as exc:
        if not args.write_manifest:
            print(f"PROVENANCE ERROR: {exc}", file=sys.stderr)
            print(
                "\nRe-run with --write-manifest to create a starter manifest, then fill in "
                "source, authority and licence before trusting the data.",
                file=sys.stderr,
            )
            return ValidationOutcome.CONFIGURATION_OR_PROVENANCE_ERROR.exit_code
        manifest = build_manifest(
            data_file,
            dataset_id=f"{args.symbol.lower()}-{interval.value}",
            source="UNVERIFIED - fill this in",
            symbol=args.symbol,
            interval=interval,
            source_timezone=args.timezone,
            bars=loaded.bars,
            note="Manifest generated by the validator. Source and licence must be completed.",
        )
        written = save_manifest(manifest, data_file)
        print(f"wrote starter manifest {written}\n")

    report = validator.validate(
        loaded.bars,
        symbol=args.symbol,
        interval=interval,
        file_path=str(data_file),
        sha256=file_sha256(data_file),
        manifest=manifest,
        load_findings=tuple(loaded.findings),
        row_count=loaded.row_count,
    )

    print(report.render_text())
    if args.json:
        destination = write_report_json(report.to_dict(), args.json)
        print(f"\nwrote {destination}")

    if manifest is not None and manifest.synthetic:
        print(
            "\nNOTE: this dataset is marked synthetic. It cannot satisfy TFEX-2 acceptance, "
            "however cleanly it validates."
        )
    print(f"\nmanifest: {manifest_path_for(data_file)}")
    return report.outcome.exit_code


if __name__ == "__main__":
    raise SystemExit(main())
